"""
All Range.
// Credits 2022 Aurélio Fernando. Code open.
// The use of this source code is governed by an MIT-style license that may
// be found in the LICENSE file.
"""

import sys
sys.path.insert(0, "allrange/")

from cockroach import developing_cockroach as developer

from packages import values

#// List of which the user will receive at the end.
elements = list()

def allrange(start, end, forElements, step = 0):
    """ This function was not made to substitude the range function(), but rather to increase
    the functionality of being able to apply range in lists. Be it a list generated by the range itself()
    or a list defined by the programmer."""
    for element in forElements:

        #// Capturing the index of the element.
        index = forElements.index(element)

        """ If it is equal to the start value, it will print.But that's just to define the beginning of our 
        Range. And basically if it's the end, it makes a break in the. """
        if index >= values.start(start):
            elements.append(element)
            if index == values.end(end):
                break
    
    #//Returning the generated list after it is handled and created.
    return elements